# @file
# SConstruct build script for this module.
#
# @author Tim Cornwell tim.cornwell@csiro.au
#

# Always import this
from conradenv import env

# create build object with library name
pkg = env.ConradPackage("conradparallel")
# add sub packages 
pkg.AddSubPackage("conradparallel")

# run the build process
pkg()

