# @file
# SConstruct build script for this module.
#
# @author Ger van Diepen (diepen AT astron nl)
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("mwcontrol")
# add sub packages 
pkg.AddSubPackage("mwcontrol")

# run the build process
pkg()

