# @file
# SConstruct build script for this module.
#
# @author Ger van Diepen (diepen AT astron nl)
#

# Always import this
from conradenv import env

# create build object with library name
pkg = env.ConradPackage("mwcommon")
# add sub packages 
pkg.AddSubPackage("mwcommon")

env.Append(CPPFLAGS=['-O2','-DCONRAD_DEBUG', '-g'])

# run the build process
pkg()

