# @file SConstruct
# SConstruct build script for this module.

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("cpdataservices")

pkg.AddSubPackage("skymodelclient")
pkg.AddSubPackage("calibrationclient")

env.Append(CCFLAGS=['-Wall'])
env.Append(CCFLAGS=['-g'])
env.Append(CCFLAGS=['-DASKAP_DEBUG'])

# run the build process
pkg()
