# @file
# SConstruct build script for this module.
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("cpingest")

pkg.AddSubPackage("ingestpipeline")

# first argument is a slice file or list of slice files
# second argument is the sub-package where the slice generated code should appear
# third argument is the location of the source file relative to this SConstruct
# file, or omit this argument for a system interface (i.e. Code/Interfaces)
#pkg.AddInterfaces("CommonTypes.ice", "interfaces")
#pkg.AddInterfaces("TypedValues.ice", "interfaces")

env.Append(CCFLAGS=['-Wall'])
env.Append(CCFLAGS=['-g'])

# run the build process
pkg()
