# The tests to be run should return 0 for success and
# > 0 for fail, accompanied by stderr detail about the failure.
# Anything else is not supported

Import("fenv")
myenv = fenv.Clone()
ftest = myenv.Program(source="tIceAppender.cc")
myenv.Alias("functest", ftest)
