import os

conrad = os.environ.get('CONRAD_PROJECT_ROOT')

Program(target = ["testfftw"], 
        source = ['testfftw.cc'],
        CCFLAGS = ['-O2','-msse3'], 
        CPPPATH = ['.',conrad+'/3rdParty/fftw/tags/fftw-3.1.2/include', 
                   conrad+'/3rdParty/casacore/tags/casacore-0.2.0/include/casacore',
                   conrad+'/Code/Components/Synthesis/synthesis/trunk/include',
                   conrad+'/Code/Base/conrad/Cc/trunk/include'],
        LIBS = ['conrad_conrad', 'casa_casa', 'conrad_synthesis', 'fftw3', 'fftw3f', 'm'], 
        LIBPATH = [conrad+'/3rdParty/fftw/tags/fftw-3.1.2/lib', 
                   conrad+'/3rdParty/casacore/tags/casacore-0.2.0/lib',
                   conrad+'/Code/Components/Synthesis/synthesis/trunk/lib',
                   conrad+'/Code/Base/conrad/Cc/trunk/lib'])