# @file SConstruct
# SConstruct build script for this module.
#
import os
import glob

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("iceinterfaces")

pkg.AddSubPackage("icegenerated")

# first argument is a slice file or list of slice files
# second argument is the sub-package where the slice generated code should appear
# third argument is the location of the source file relative to this SConstruct
# file, or omit this argument for a system interface (i.e. Code/Interfaces)
#
icefiles = glob.glob("../../slice/current/*.ice")
icefiles = [ os.path.split(p)[-1] for p in icefiles ]
# These are the ASKAPsoft component interfaces:
pkg.AddInterfaces(icefiles, "icegenerated")

# This package should be built as a shared library 
pkg.build_shared = True 

# This package should not build an archive/static library
pkg.build_static = False

env.Append(CCFLAGS=['-Wall'])
env.Append(CCFLAGS=['-g'])

# run the build process
pkg()
