# @file SConstruct
# SConstruct build script for this module.
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("correlatorsim")

pkg.AddSubPackage("simplayback")
pkg.AddSubPackage("cpinterfaces")

# first argument is a slice file or list of slice files
# # second argument is the sub-package where the slice generated code should appear
# # third argument is the location of the source file relative to this SConstruct
# # file, or omit this argument for a system interface (i.e. Code/Interfaces)
pkg.AddInterfaces("CommonTypes.ice", "cpinterfaces")
pkg.AddInterfaces("TypedValues.ice", "cpinterfaces")

env["CC"] = "mpicc"
env["CXX"] = "mpicxx"
env["LINK"] = "mpicxx"
env["SHLINK"] = "mpicxx"
env.Append(CCFLAGS=['-O2', '-g'])

# run the build process
pkg()
