# @file SConstruct
# SConstruct build script for this module.
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("correlatorsim")

pkg.AddSubPackage("simplayback")

env.Append(CCFLAGS=['-g'])

# run the build process
pkg()
