#!/bin/bash -l
#PBS -l nodes=2:ppn=1
#PBS -N stdtest
#PBS -m e
#PBS -v ASKAP_ROOT
cd $PBS_O_WORKDIR

module load openmpi

echo "Extracting 10uJy model" > stdtest.$PBS_JOBID.out

tar zxvf ${ASKAP_ROOT}/Code/Components/Synthesis/testdata/trunk/simulation/models/10uJy.model.small.tgz >> stdtest.$PBS_JOBID.out

export AIPSPATH=${ASKAP_ROOT}/Code/Components/Synthesis/testdata/trunk

echo "Running csimulator to create MeasurementSet for a single pointing" >> stdtest.$PBS_JOBID.out
mpirun -x AIPSPATH time ${ASKAP_ROOT}/Code/Components/Synthesis/synthesis/trunk/bin/csimulator.sh -inputs stdtest.in >> stdtest.$PBS_JOBID.out

echo "Running cimager to form Clean image of single pointing" >> stdtest.$PBS_JOBID.out
mpirun -x AIPSPATH time ${ASKAP_ROOT}/Code/Components/Synthesis/synthesis/trunk/bin/cimager.sh -inputs stdtest.in >> stdtest.$PBS_JOBID.out
