#!/bin/bash -l
#PBS -l nodes=2:ppn=1
#PBS -N stdtest
#PBS -m e
#PBS -v ASKAP_ROOT
cd $PBS_O_WORKDIR

module load openmpi

export AIPSPATH=${ASKAP_ROOT}/Code/Components/Synthesis/testdata/trunk

echo "This is the ASKAPsoft stdtest. It will run for about 20-30 minutes."  | tee stdtest.$PBS_JOBID.out

echo "Extracting 10uJy model" | tee -a stdtest.$PBS_JOBID.out

tar zxvf ${ASKAP_ROOT}/Code/Components/Synthesis/testdata/trunk/simulation/models/10uJy.model.small.tgz  | tee -a stdtest.$PBS_JOBID.out

export AIPSPATH=${ASKAP_ROOT}/Code/Components/Synthesis/testdata/trunk

echo "Running csimulator to create MeasurementSet for a single pointing"  | tee -a stdtest.$PBS_JOBID.out
mpirun -x AIPSPATH time ${ASKAP_ROOT}/Code/Components/Synthesis/synthesis/trunk/bin/csimulator.sh -inputs stdtest.simulator.in  | tee -a stdtest.$PBS_JOBID.out

echo "Running cimager to form Clean image of single pointing"  | tee -a stdtest.$PBS_JOBID.out
mpirun -x AIPSPATH time ${ASKAP_ROOT}/Code/Components/Synthesis/synthesis/trunk/bin/cimager.sh -inputs stdtest.dirty.in  | tee -a stdtest.$PBS_JOBID.out

echo "Running cimager to form Dirty image of single pointing"  | tee -a stdtest.$PBS_JOBID.out
mpirun -x AIPSPATH time ${ASKAP_ROOT}/Code/Components/Synthesis/synthesis/trunk/bin/cimager.sh -inputs stdtest.clean.in  | tee -a stdtest.$PBS_JOBID.out
