# @file
# SConstruct build script for this module.
# This is currently a test case, please edit this comment when deemed stable
#
# @author Malte Marquarding <Malte.Marquarding@csiro.au>
#

# Always import this
from conradenv import env

env.Append(CCFLAGS=['-O2'])

# create build object with library name
pkg = env.ConradPackage("synthesis")

# add sub packages 
pkg.AddSubPackage("measurementequation")
pkg.AddSubPackage("dataaccess")
pkg.AddSubPackage("gridding")

# run the build process
pkg()

