# @file
# SConstruct build script for this module.
# Package dependencies are read from 'dependencies.default'
#
# @author Malte Marquarding <Malte.Marquarding@csiro.au>
#

# Always import this
from askapenv import env

env.AppendUnique(CCFLAGS='-g')
env.AppendUnique(CCFLAGS='-O3')
env.AppendUnique(CCFLAGS='-DASKAP_DEBUG')
env.Append(universal=0)

# create build object with library name
pkg = env.AskapPackage("scimath")

# add sub packages 
pkg.AddSubPackage("fitting")
pkg.AddSubPackage("utils")
pkg.AddSubPackage("fft")

# run the build process
pkg()
