# @file SConstruct
# SConstruct build script for this module.
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("cpcommon")

pkg.AddSubPackage("cpcommon")

env.Append(CCFLAGS=['-Wall'])
env.Append(CCFLAGS=['-g'])

# run the build process
pkg()
