#!/bin/sh

# Run the tSocketConnection test program by starting it twice,
# once as server and once as client.
./tSocketConnection 3851 > tSocketConnection_tmp.outs1 &
./tSocketConnection 3851 localhost > tSocketConnection_tmp.outc1

# If something went wrong, kill the background process (if it's still running)
# and exit.
STATUS=$?
if [ $STATUS != 0 ]; then
  if kill -0 $! 2>/dev/null; then 
    kill -9 $! 2>/dev/null
  fi
  exit $STATUS
fi

# Output the result in order.
echo "Run1 ..."
cat tSocketConnection_tmp.outs1 tSocketConnection_tmp.outc1


# Do another run, now starting the client before the server.
./tSocketConnection 3851 localhost > tSocketConnection_tmp.outc2 &
./tSocketConnection 3851 > tSocketConnection_tmp.outs2

# If something went wrong, kill the background process (if it's still running)
# and exit.
STATUS=$?
if [ $STATUS != 0 ]; then 
  if kill -0 $! 2>/dev/null; then 
    kill -9 $! 2>/dev/null
  fi
  exit $STATUS
fi

# Output the result in order.
echo "Run2 ..."
cat tSocketConnection_tmp.outs2 tSocketConnection_tmp.outc2
exit 0
