# @file
# SConstruct build script for this module.
#
# @author Tim Cornwell tim.cornwell@csiro.au
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("askapstream")
# add sub packages 
pkg.AddSubPackage("askapstream")

# run the build process
pkg()

