# @file
# SConstruct build script for this module.
# This is currently a test case, please edit this comment when deemed stable
#
# @author Malte Marquarding <Malte.Marquarding@csiro.au>
#

# Always import this
from conradenv import env
import os

os.environ['AIPSPATH']=os.environ['CONRAD_PROJECT_ROOT']+'/Code/Components/Synthesis/testdata/trunk'
env["ENV"]["AIPSPATH"] = os.environ['AIPSPATH']

#env.Append(CCFLAGS=['-O2', '-DCONRAD_DEBUG', '-DCONRAD_GRID_WITH_BLAS', '-g'])
env.Append(CCFLAGS=['-O2', '-DCONRAD_DEBUG', '-g'])
env.Append(universal=0)

# create build object with library name
pkg = env.ConradPackage("synthesis")

# add sub packages 
pkg.AddSubPackage("measurementequation")
pkg.AddSubPackage("dataaccess")
pkg.AddSubPackage("gridding")
pkg.AddSubPackage("parallel")
pkg.AddSubPackage("fft")
pkg.AddSubPackage("simulation")

# run the build process
pkg()

