# @file
# SConstruct build script for this module.
# This is currently a test case, please edit this comment when deemed stable
#
# @author Malte Marquarding <Malte.Marquarding@csiro.au>
#

# Always import this
from conradenv import env
import os

os.environ['AIPSPATH']=os.environ['CONRAD_PROJECT_ROOT']+'/Code/Components/Synthesis/testdata/trunk'

env.Append(CCFLAGS=['-O2','-DCONRAD_DEBUG', '-g','-DUSE_NOSOCKETS'])

env["CC"] = "mpicc"
env["CXX"] = "mpicxx"
env["LINK"] = "mpicxx"
env["SHLINK"] = "mpicxx"
env.AppendUnique(CPPFLAGS=['-DHAVE_MPI'])

# create build object with library name
pkg = env.ConradPackage("synthesis")

# add sub packages 
pkg.AddSubPackage("measurementequation")
pkg.AddSubPackage("dataaccess")
pkg.AddSubPackage("gridding")

# run the build process
pkg()

