# @file
# SConstruct build script for this module.
#
# @author Ger van Diepen (diepen AT astron nl)
#

# Always import this
from askapenv import env

env.Append(CCFLAGS=['-O2','-DASKAP_DEBUG', '-g', '-DUSE_NOSOCKETS'])

# create build object with library name
pkg = env.AskapPackage("mwcommon")

# add sub packages 
pkg.AddSubPackage("mwcommon")

# run the build process
pkg()

