# @file
# SConstruct build script for this module.
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("mq")

pkg.AddSubPackage("broker")
pkg.AddSubPackage("blobutils")
pkg.AddSubPackage("dataaccess")

env.Append(CCFLAGS=['-Wall'])
env.Append(CCFLAGS=['-g'])
env.Append(CCFLAGS=['-DASKAP_DEBUG'])

# run the build process
pkg()
