# @file
# SConstruct build script for this module.
#
# @author Matthew Whiting matthew.whiting@csiro.au
#

# Always import this
from askapenv import env

env.Append(CCFLAGS=['-DHAVE_LONG_LONG'])

# create build object with library name
pkg = env.AskapPackage("simulations")
# add sub packages 
pkg.AddSubPackage("FITS")
pkg.AddSubPackage("makemodelslice")
pkg.AddSubPackage("simulationutilities")

# run the build process
pkg()

