# @file
# SConstruct build script for this module.
#
# @author Matthew Whiting matthew.whiting@csiro.au
#

# Always import this
from askapenv import env

env.Append(CCFLAGS=['-O2', '-g', '-DHAVE_LONG_LONG', '-DASKAP_DEBUG'])

# create build object with library name
pkg = env.AskapPackage("simulations")
# add sub packages 
pkg.AddSubPackage("FITS")
pkg.AddSubPackage("simulationutilities")

## Disable "shared" as Duchamp is not built with fPIC
#pkg.build_shared = False;
#pkg.build_static = True;

# run the build process
pkg()

