# @file
# SConstruct build script for this module.
# This is currently a test case, please edit this comment when deemed stable
#
# @author Malte Marquarding <Malte.Marquarding@csiro.au>
#

# Always import this
from askapenv import env
import os

if 'AIPSPATH' not in os.environ:
   os.environ['AIPSPATH']=os.environ['ASKAP_ROOT']+'/Code/Base/accessors/current'
env["ENV"]["AIPSPATH"] = os.environ['AIPSPATH']

env.Append(CCFLAGS=['-O2', '-DASKAP_DEBUG', '-g'])

# Optimization for complex arithmetic. The functionality this flag enables
# was default behaviour prior to GCC 4.3.
env.Append(CCFLAGS=['-fcx-limited-range'])

env.Append(universal=0)

# create build object with library name
pkg = env.AskapPackage("swcorrelator")
env["ENV"]["AIPSPATH"] = os.environ['AIPSPATH']

# add sub packages 
pkg.AddSubPackage("swcorrelator")
pkg.AddSubPackage("dataformats")

# run the build process
pkg()

