# @file
# SConstruct build script for this module.
#
# @author Tim Cornwell tim.cornwell@csiro.au
#

# Always import this
from conradenv import env

env.Append(CCFLAGS=['-O2', '-DHAVE_LONG_LONG', '-DCONRAD_DEBUG', '-g'])

# create build object with library name
pkg = env.ConradPackage("analysis")
# add sub packages 
pkg.AddSubPackage("parallelanalysis")

# run the build process
pkg()

