# @file
# SConstruct build script for this module.
#
# @author Tim Cornwell tim.cornwell@csiro.au
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("analysisutilities")
# add sub packages 
pkg.AddSubPackage("modelcomponents")
pkg.AddSubPackage("casainterface")
pkg.AddSubPackage("coordutils")
pkg.AddSubPackage("mathsutils")
pkg.AddSubPackage("analysisparallel")
pkg.AddSubPackage("cosmology")

env.Append(CCFLAGS=['-DHAVE_LONG_LONG'])

# run the build process
pkg()

