# @file
# SConstruct build script for this module.
#
# @author Tim Cornwell tim.cornwell@csiro.au
#

# Always import this
from askapenv import env

env.Append(CCFLAGS=['-Wall', '-O2', '-g', '-DHAVE_LONG_LONG', '-DASKAP_DEBUG'])

# create build object with library name
pkg = env.AskapPackage("analysisutilities")
# add sub packages 
pkg.AddSubPackage("modelcomponents")
pkg.AddSubPackage("coordconversions")
pkg.AddSubPackage("maths")
pkg.AddSubPackage("analysisparallel")

# run the build process
pkg()

