# @file
# SConstruct build script for this module.
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("pipelinetasks")

pkg.AddSubPackage("cmodel")

env.Append(CCFLAGS=['-Wall'])
env.Append(CCFLAGS=['-g'])
env.Append(CCFLAGS=['-O2'])
env.Append(CCFLAGS=['-DASKAP_DEBUG'])

# Use MPI compiler wrapper
env["CC"] = "mpicc"
env["CXX"] = "mpicxx"
env["LINK"] = "mpicxx"
env["SHLINK"] = "mpicxx"

# run the build process
pkg()
