# SConstruct build script for this module.
#
# @author Tim Cornwell tim.cornwell@csiro.au
#

# Always import this
from askapenv import env
import os
import askapdev.rbuild.utils as utils

if 'AIPSPATH' not in os.environ:
   os.environ['AIPSPATH']=os.environ['ASKAP_ROOT']+'/Code/Base/accessors/current'
env["ENV"]["AIPSPATH"] = os.environ['AIPSPATH']

env.AppendUnique(CCFLAGS=['-DHAVE_LONG_LONG'])

# NOTE: This is a temporary workaround for the issue described in Jira issue
# ASKAPSDP-1628. Currently the only platform known to need this is Ubuntu
# 14.04. Ubuntu 14.10 (i.e. the following release) does not require this.
platform = utils.get_platform()
if platform['distribution'] == 'Ubuntu' and platform['version'] == '14.04':
    env.Append(LINKFLAGS=['-Wl,--no-as-needed'])

# create build object with library name
pkg = env.AskapPackage("analysis")
# add sub packages 
pkg.AddSubPackage("parallelanalysis")
pkg.AddSubPackage("duchampinterface")
pkg.AddSubPackage("sourcefitting")
pkg.AddSubPackage("extraction")
pkg.AddSubPackage("parametrisation")
pkg.AddSubPackage("polarisation")
pkg.AddSubPackage("preprocessing")
pkg.AddSubPackage("patternmatching")
pkg.AddSubPackage("outputs")
pkg.AddSubPackage("catalogues")

# run the build process
pkg()

