# @file SConstruct
# SConstruct build script for this module.
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("correlatorsim")

pkg.AddSubPackage("simplayback")

env["CC"] = "mpicc"
env["CXX"] = "mpicxx"
env["LINK"] = "mpicxx"
env["SHLINK"] = "mpicxx"

env.AppendUnique(CCFLAGS='-O3')
env.AppendUnique(CCFLAGS='-g')

# run the build process
pkg()
