# @file
# SConstruct build script for this module.
# Package dependencies are read from 'dependencies.default'
#
# @author Malte Marquarding <Malte.Marquarding@csiro.au>
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("askap")

# add sub packages 
pkg.AddSubPackage("askap")
pkg.AddSubPackage("profile")

# run the build process
pkg()
