import os

conrad = os.environ.get('CONRAD_PROJECT_ROOT')

Program(target = "testfftw", 
        source = "testfftw.cc",
        CCFLAGS = ['-O2','-g'], 
        CPPPATH = ['.',conrad+'/3rdParty/fftw/tags/fftw-3.1.2/include', 
                   conrad+'/3rdParty/casacore/tags/casacore-0.2.0/include/casacore'],
        LIBS = ['fftw3','fftw3f','m', 'casa_casa'], 
        LIBPATH = [conrad+'/3rdParty/fftw/tags/fftw-3.1.2/lib', 
                   conrad+'/3rdParty/casacore/tags/casacore-0.2.0/lib'])