# @file
# SConstruct build script for this module.
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("parallelframework")

# add sub packages 
pkg.AddSubPackage("processingsteps")
pkg.AddSubPackage("communicators")
pkg.AddSubPackage("application")

# run the build process
pkg()

