# The tests to be run should return 0 for success and
# > 0 for fail, accompanied by stderr detail about the failure.
# Anything else is not supported

Import("functestenv")
myenv = functestenv.Clone()

tests = []

# build a test implicitly
#ftest = myenv.Program(source="a.cc")
#myenv.Alias("functest", ftest)

ftest = myenv.FuncTest(source=tests)
myenv.Alias("functest", ftest)
