# @file
# SConstruct build script for this module.
# Package dependencies are read from 'dependencies.default'
#
# @author Malte Marquarding <Malte.Marquarding@csiro.au>
#

# Always import this
from conradenv import env

env.Append(CCFLAGS=['-O2'])
#env.Append(CCFLAGS=['-Wall'])
#env.Append(CCFLAGS=['-DHAVE_AIPSPP'])

# create build object with library name
pkg = env.ConradPackage("scimath")

# add sub packages 
pkg.AddSubPackage("fitting")

# run the build process
pkg()
