# @file
# SConstruct build script for this module.
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("components")

pkg.AddSubPackage("components")

env.Append(CCFLAGS=['-g'])
env.Append(CCFLAGS=['-O3'])
env.Append(CCFLAGS=['-DASKAP_DEBUG'])

# run the build process
pkg()
