# @file
# SConstruct build script for this module.
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("imager")

pkg.AddSubPackage("distributedimager")
pkg.AddSubPackage("messages")

env["CC"] = "mpicc"
env["CXX"] = "mpicxx"
env["LINK"] = "mpicxx"
env["SHLINK"] = "mpicxx"

env.AppendUnique(CCFLAGS='-g')
env.AppendUnique(CCFLAGS='-O3')

# run the build process
pkg()
