# @file
# SConstruct build script for this module.
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("imager")

pkg.AddSubPackage("distributedimager")
pkg.AddSubPackage("messages")

# Disable "shared" as MPE2 is not built with fPIC
pkg.build_shared = False;
pkg.build_static = True;

env.AppendUnique(CCFLAGS=['-g'])
env.AppendUnique(CCFLAGS=['-O3'])

# run the build process
pkg()
